baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "OVN, Open Virtual Network"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/ovn-org/ovn-website/edit/main/src/content/"
  description = "Documentation website for the OVN project"
  author = "The OVN community"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "OVN project documentation website"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-book'></i> Documentation"
url = "https://docs.ovn.org"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/ovn-org/"
weight = 20

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-envelope'></i> User mailing list"
# url = "https://bit.ly/submariner-users"
# weight = 20

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-envelope'></i> Devel mailing list"
# url = "https://bit.ly/submariner-dev"
# weight = 30

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-video'></i> Youtube demos"
# url = "https://www.youtube.com/channel/UCZ3brSgl2v4boglZoeChClQ/videos"
# weight = 40

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bookmark'></i> Twitter"
# identifier = "twitter"
# url = "https://twitter.com/submarinerio"
# weight = 50

[Languages.es]
title = "Proyecto OVN, documentación"
weight = 2
languageName = "Spanish"

[[Languages.es.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
identifier = "ds"
url = "https://github.com/ovn-org/"
weight = 10


# [[Languages.es.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-envelope'></i>Lista de correo (usuarios)"
# url = "https://bit.ly/submariner-users"
# weight = 20

# [[Languages.es.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-envelope'></i>Lista de correo (desarrolladores)"
# url = "https://bit.ly/submariner-dev"
# weight = 30

# [[Languages.es.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-video'></i> Demos youtube"
# url = "https://www.youtube.com/channel/UCZ3brSgl2v4boglZoeChClQ/videos"
# weight = 40

# [[Languages.es.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bookmark'></i> Twitter"
# identifier = "twitter"
# url = "https://twitter.com/submarinerio"
# weight = 50

